### ISSUE TITLE
Mod Data has data error on Second Decimal place.

### ISSUE THREAD

**Issue by elric667** [jedi-gg/swgoh.gg.public#203]
Looks like the second decimal place is being truncated by your data pull compared to round that is in Game.
Here is a character that has the error and there is many more but this is a good example
https://swgoh.gg/u/gulliver-skidmore-iii/collection/47/magmatrooper/

![gamescreenshot](https://user-images.githubusercontent.com/25038394/37247009-708b5d90-2471-11e8-9bf8-96fb69572d4d.png)
![sgwoh gg](https://user-images.githubusercontent.com/25038394/37247010-76b58a56-2471-11e8-9cb8-b892e136475a.png)

Attaching one file from the game screen shot of the mod value and another from swgoh.gg

I can get other versions of the same information if you need.

Secondary Stat in game is 0.96% in swgoh.gg same secondary stat is 0.95%

**Comment by elric667** [comment]
Wondering if this was fixed or corrected?

**Comment by danpaulson** [comment]
Will look into this and reopen - sorry was just clearing out super old, likely fixed issues.

**Comment by scoot1585** [comment]
This one was weird to figure out.  So the data they give us has two values.  A stat value ex `29` and an unscaled decimal value of `299000`.  I didn't realize they actually lost precision in the different properties.  So I updated the code to use the more precise one.  

We need to trigger a full sync for everyone to happen which won't prob happen right away, but you can trigger this to update on your own account with a manual update.

Thanks for the report and this helped solve issues with my slight unit stat calculation errors because of these rounding issues.
