### ISSUE TITLE
Squad template pages will not sort properly by user name

### ISSUE THREAD

**Issue by jasonluc23** [jedi-gg/swgoh.gg.public#259]
https://swgoh.gg/g/256/elite-casual/squad-templates/1176/

When sorting by Name on squad template pages, it's out of order.

https://swgoh.gg/g/256/elite-casual/unit-search/#AAYLASECURA

Similarly, is it possible to add sort options on the unit search pages?

Thanks!

**Comment by scoot1585** [comment]
Thanks for reporting the first one, I just deployed a fix.  It was technically sorting it by the URL of each guild member which is why it seemed out of order. 

As for the second suggestion, we have that on the list of TODOs.  The whole unit search UI is due for an overhaul, and it is not super easy to just add that in, so we just ask for ya patience.

Thanks for using the site!
