### ISSUE TITLE
Guild Squad template does not work

### ISSUE THREAD

**Issue by celsogbj** [jedi-gg/swgoh.gg.public#409]
The Guild Squad Template is not working.

I created this template: https://swgoh.gg/g/2430/team-treta/squad-templates/46832/

And it doesn’t show any squad.

I am using Safari / iPhone X

**Comment by Twizted25ID** [comment]
I can attest to this.  I understand there was a server move, but after weeks of dealing with registration issues, we finally have our guild completely registered for HSTR prep.

https://swgoh.gg/g/5686/drunkenspacers/squad-templates/47177/
Now we can't assign farms because the squad templates are broken (But was working fine when we couldn't get everyone registered 🙄)

This has been a very trying few weeks for me as an avid SWGOH.gg user.  I hope these issues may be resolved soon.

This issue persists across all 6 templates that we have set up.

(That is, for clarity, all templates show on the main template page.  However, when using a template and going to the individual page, a message of "An error has occured." displays and no members or their characters display.  I have noticed this going on since last Thursday, 9/20/18, consistently.)

I acknowledge that in times of struggle, negativity is overwhelming.  And in times of prosperity, positivity is lacking in comparison.  So with that said, I would like to state that I love SWGOH.gg.  It is invaluable for myself and a couple other officers in my guild and has always been an incredible resource.  I just never expected a server move to go so poorly and have such adverse effects.

Thank you for your time and all that you've done for us SWGOH players.

**Comment by danpaulson** [comment]
@Twizted25ID are you available on Discord? Need someone to walk through to debug this as it's super inconsistent. I'm Sep#7102 if so.

**Comment by Twizted25ID** [comment]
Yeah Im not at home at the moment but will be soon.

**Comment by Twizted25ID** [comment]
I will be home shortly @danpaulson

**Comment by bakou-swgoh** [comment]
I have the same issue for my guild. 
For example: https://swgoh.gg/g/11104/an-enterprising-starship/squad-templates/69/

In case that would help

**Comment by danpaulson** [comment]
Hey fellas - this fixed now? All seem to be loading for me.

**Comment by bakou-swgoh** [comment]
Yes it’s working thanks 🙏🏻

**Comment by celsogbj** [comment]
Working for me too. Thank you very much!

Could you take a look on issue #408?
https://github.com/jedi-gg/swgoh.gg.public/issues/408

Also iPhone related
