### ISSUE TITLE
Ship Arena Chart Sync

### ISSUE THREAD

**Issue by Chakyth** [jedi-gg/swgoh.gg.public#489]
Hey Mates,

the Chart for the Ship Arena payout is syncing about 20 minutes late since 2 days. Arena Placements usually changes during that time due to upcoming payouts. Please adjust back to 1 Minute after payout.

Thanks in advance!

**Comment by sanktanglia** [comment]
Unfortunately we cant scan all ships within 1 minute because on some hours we have to scan 50k+ channels for an hour, so theres no way we can get it all done in a minute. We recently changed how we pull back the data which is causing where you are in the queue to be different, so while yours is delayed, others are scanning 1 minute after. We are looking to sort this by rank, so higher ranks get scanned first, and to expand our resources we put towards this, but fleet arena is given less resources due to it not being as important a feature as normal arena. If you can give me your ally code I can see how the tweaks I make affect your sync time

**Comment by Chakyth** [comment]
Hi!
My ally Code is 646-478-117
https://swgoh.gg/p/646478117/

Thanks for the Support!

**Comment by PixEye** [comment]
Hello, the problem is back again for almost a week (no fleet arena rank) and all profiles I check. :-/

**Comment by scobenes** [comment]
This is most likely an old bug
