### ISSUE TITLE
Rey's Millennium Falcon

### ISSUE THREAD

**Issue by ryan-shah** [jedi-gg/swgoh.gg.public#501]
When pulling [ship data](https://swgoh.gg/ships/) Rey's Millennium Falcon is referred to as "Rey's Millennium Falcon", but when pulling [user data](https://swgoh.gg/p/613273547/ships/) its referred to as "Millennium Falcon (Ep VII)". This causes an issue when comparing a player's ship to the list of known ships.

https://swgoh.gg/ships/reys-millennium-falcon/
https://swgoh.gg/p/613273547/ships/millennium-falcon-ep-vii

**Comment by arctouch-raphaellupchinski** [comment]
Having the same issue when comparing Ships and characters data from API.
However, even some users on our guild have the `Millennium Falcon (Ep VII)` and others have `Rey's Millennium Falcon`.

Here's a char with all available ships from our guild:
https://swgoh.gg/p/658835177/ships/

Heres one with fewer ships, but with the MF(EP7) instead:
https://swgoh.gg/p/361137392/ships/

The https://swgoh.gg/api/ships/ call returns as `Rey's Millennium Falcon`, even though the baseId of that ship is `MILLENNIUMFALCONEP7`

**Comment by sanktanglia** [comment]
in general you always want to use the base id when comparing stuff as it wont change while the name of the ship/units might. the issue is our caching doesnt see the name change as something it needs to update so people who had the ship already dont get the new name update on their data, we are looking at ways to trigger that

**Comment by arctouch-raphaellupchinski** [comment]
Cool, I'll update my scripts to use the base id as it sure does look more reliable :)
Thanks for the input!
