### ISSUE TITLE
Export - csv/excel spreadsheet

### ISSUE THREAD

**Issue by amelsen** [jedi-gg/swgoh.gg.public#579]
Is it possible to get an export feature, to withdraw your characters/ships, etc to a spreadsheet format, allowing an easier filterable overview_

**Comment by mutexjp** [comment]
@amelsen i'm not aware of a feature on swgoh.gg that exports directly to spreadsheet, but there is a project that gives you a google spreadsheet that will pull from swgoh.gg: https://github.com/PopGoesTheWza/swgoh-sheets-core

**Comment by amelsen** [comment]
!

**Comment by AdmiralP** [comment]
@amelsen - I may have an easier option for you in the form of a Discord bot. It provides a xlsx spreadsheet with all details (except relic info) on the entire guild regardless of whether or not they have an account on swgoh.gg. I've posted an example image below. If you are interested I can get you lined up with the setup process via Discord. You can find my Discord info listed on my bio page by clicking on my avatar.

Since I am not certain if it would be considered a competing product of swgoh.gg or not I will opt to refrain from giving any more details than that. I really enjoy both options and use each often.

![image](https://user-images.githubusercontent.com/33196541/124785590-9954b880-df0c-11eb-9821-403d4ddb9d67.png)
