### ISSUE TITLE
402 problem for gac history data

### ISSUE THREAD

**Issue by DylanTusler** [jedi-gg/swgoh.gg.public#603]
Hi I am browsing GAC history for my guild. After looking at GAC history for around 5 or 6 guild members, I now get 402 errors on any other GAC history page I go to (including my own.)

I don't feel like I am flooding the servers or anything, spending maybe 30-40 seconds looking at each page. Also this limitation never seems to change. I have been unable to view my own GAC history for almost 24 hours now. I can still visit and revisit the history for the members I could originally visit.

For instance, no matter how often I look I can see this GAC History page:
https://swgoh.gg/p/771515721/gac-history/?gac=4&r=2
but no matter how long I wait, I can't see this one. I always get a 402 error:
https://swgoh.gg/p/445277377/gac-history/?gac=4&r=2

Is there some other thing I should be doing?

**Comment by sanktanglia** [comment]
we currently have a limit on how many pages you can visit, in order to prevent people from scraping the website in order to get this information. I dont want to say how long/how many triggers it as then people will set their bots just below that number, but the cache will clear and then youll be able to access it again. Note that if you are scraping the people via some sort of tool then itd block you as well. If you feel this is in error you can supply your ip and ill check it on our backend to see how many usages we see

**Comment by DylanTusler** [comment]
OK, understood. WAI. I guess I wait until there is a usable way of viewing this info apart from your site. I can see  my gac now finally so the cache must be clear.
