### ISSUE TITLE
Player ID is already attached to an account.

### ISSUE THREAD

**Issue by JustOutOfTheBox** [jedi-gg/swgoh.gg.public#661]
Dear Staff,

I can't log in with my account OutOfTheBox on swgoh.gg
I try to request a new password via email, but I don't receive any reply, any spam box, nothing.
I've tried to subscribe again, but there is an error message because I'm already registered.
this is the error: *** Player ID is already attached to an account.**
https://swgoh.gg/settings/sync/ 
Can you reset my account please? so I can subscribe again. (ally code: 567-757-333)

thank you

**Comment by nukrozxc** [comment]
Hi;
I have the same problem. Is there a solution to this issue? Can you help us?

I sent an e-mail about this          =>       "swgohgg@gmail.com"        =>        but there was no return..

thanks.

**Comment by Vinc21** [comment]
Dear Staff,

I can't log in with my account OutOfTheBox on swgoh.gg
I try to request a new password via email, but I don't receive any reply, any spam box, nothing.
I've tried to subscribe again, but there is an error message because I'm already registered.
this is the error: *** Player ID is already attached to an account.**
https://swgoh.gg/settings/sync/
Can you reset my account please? so I can subscribe again. (ally code:839-738-343 )

thank you

**Comment by scobenes** [comment]
For anyone else with a similar issue: Come into our discord and there are instructions in #i-have-a-problem channel that outline common help and what info we may need to help with this situation.
