### ISSUE TITLE
Cannot sync account

### ISSUE THREAD

**Issue by MattGomes** [jedi-gg/swgoh.gg.public#667]
Cannot sync my account after just creating it even though it says that my sync status is 'active'.  When I attempt to sync, it takes me to the 404 page.  In my account settings page I can see that my ally code was pulled in correctly, but my ally code URL also takes me to the 404 page: https://swgoh.gg/p/258797726/

**Comment by AdmiralP** [comment]
@MattGomes - I do not work with or on the website, but I can tell you that the link you provided is inaccurate. I am not sure why it directed you to that, and that may be another issue altogether. 

The last digits in the URL are always your Ally Code, and those are limited to nine digits. Your URL provided has ten digits. Try updating the URL so that it reads like the following to see if you get better results:

https://swgoh.gg/p/«PutYourAllyCodeHere»

As an example, here is mine, with my ally code 112-262-571: 

https://swgoh.gg/p/112262571

**Comment by MattGomes** [comment]
Looks like it's working now - all good.
